### ISSUE TITLE
HTTPS request doesn't work when disable_ssl_certificate_validation = True

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#173]
_From [kvvier](https://code.google.com/u/kvvier/) on September 06, 2011 04:05:20_

What steps will reproduce the problem? h = httplib2.Http(cache="C:\\Temp\\.cache")
h.disable_ssl_certificate_validation=True
out, err = h.request("https://mail.google.com" #uri doesn't matter
print(out['status']) What is the expected output? What do you see instead? I expect to get '200' printed to stdout, 
instead I get:
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED What version of the product are you using? On what operating system? httplib2-0.7.1 (CPython 3.2.1 64-bit, Windows 7 Enterprise 64-bit) Please provide any additional information below. Changing (in HTTPSConnectionWithTimeout constructor):
http.client.HTTPSConnection.__init__(self, host, port=port,
    key_file=key_file, cert_file=cert_file, timeout=timeout, 
    context=context,
    check_hostname= True)

to:

http.client.HTTPSConnection.__init__(self, host, port=port,
    key_file=key_file, cert_file=cert_file, timeout=timeout, 
    context=context,
    check_hostname= disable_ssl_certificate_validation ^ True)

solves issue.(no errors, response as expected)

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=173_

**Comment by jevonearth** [comment]
Is there blocker preventing the provided pull requests from being merged? This bug is holding back adoption of python3. :(

**Comment by wassname** [comment]
Please merge this, my oauth2client also fails due to this bug

**Comment by mynameisfiber** [comment]
Is there a way I can help to get this merged? 2 years old and it's still an issue.

**Comment by pythonishvili** [comment]
We long for the day it's merged. Indeed.

**Comment by cbetti** [comment]
Hi jcgregorio, does the recent update imply the fix has been incorporated? (I hope!)

**Comment by cdent** [comment]
If this is still relevant please re open it at https://github.com/httplib2/httplib2/issues

See: http://bitworking.org/news/2016/03/an_update_on_httplib2
