### ISSUE TITLE
Support for proxy... (Python 3)

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#205]
_From [davispuh](https://code.google.com/u/davispuh/) on March 17, 2012 22:16:24_

Using python 3 and SocksiPy library (socksipy-branch http://code.google.com/p/socksipy-branch/ )
(socksipy-branch is working with python 3)

but
import httplib2
import socks

h = httplib2.Http(proxy_info = httplib2.ProxyInfo(socks.PROXY_TYPE_HTTP, ProxyHostname, ProxyPort))
r,c = h.request(" http://automation.whatismyip.com/n09230945.asp" )

gives no effect, while:

socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, Hostname, Port)
socks.wrapmodule(httplib2)
h = httplib2.Http()
r,c = h.request(" http://automation.whatismyip.com/n09230945.asp" )

does work :)

I would prefer the former and full support for proxies ;)

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=205_

**Comment by iPotap** [comment]
Didn't seem to work for me. Any other ways? I'm trying to access Google Analytics API behind a proxy and wasted whole day in vain.

**Comment by jayvdb** [comment]
http://bitworking.org/news/2016/03/an_update_on_httplib2

**Comment by sbmzhcn** [comment]
```
socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, Hostname, Port)
socks.wrapmodule(httplib2)
h = httplib2.Http()
r,c = h.request(" http://automation.whatismyip.com/n09230945.asp" )
```

this works for me for Google Analytics API

**Comment by enricofer** [comment]
socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, Hostname, Port, username=user, password=pwd)

**Comment by humanusa** [comment]
Any idea how i can make it work behind basic proxy with authentication. 

import httplib2
import socks

socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, '10.74.91.103', 80)
socks.wrapmodule(httplib2)

http = httplib2.Http()
r,c = http.request("http://www.example.com", "GET")
