### ISSUE TITLE
Failed to retrieve the certificate if it has 'subjectAltName' but no 'dns'

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#208]
_From [dingyichen](https://code.google.com/u/dingyichen/) on May 03, 2012 03:13:01_

Some certificates have subjectAltName, but no 'dns' attribute associated with it. Thus it failed to get the host and produces error:
"Server presented certificate that does not match host <HostName> What steps will reproduce the problem? 1. Find some certificate with subjectAltName, but dns is missing
2. Try to connect with this certificate 3. What is the expected output? 
Connection succeed without error.

What do you see instead?
Failed to find host information from certification, thus following error is shown:
error: Server presented certificate that does not match host What version of the product are you using? On what operating system? python-httplib2-0.7.4 Please provide any additional information below. Proposed patch attached.

**Attachment:** [python-httplib2.getCertHost.patch](http://code.google.com/p/httplib2/issues/detail?id=208)

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=208_

**Comment by tremby** [comment]
This issue is causing me headaches. Is any of these patches suitable? If so, any chance it can be merged?
