### ISSUE TITLE
SSL certificate hostname mismatch is checked only once

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#243]
_From [rpodoly...@mirantis.com](https://code.google.com/u/104933407216723277538/) on April 23, 2013 03:54:47_

What steps will reproduce the problem? 1. Make a request to an HTTPS server with a domain name not matching one that is specified in the corresponding SSL certificate.
2. Repeat the request once again.

Expected behavior: both requests fail with CertificateHostnameMismatch error.

Actual behavior: the first request fails with CertificateHostnameMismatch, but the second one succeeds.

The problem is caused by incorrect error handling in connect() method of HTTPSConnectionWithTimeout class. The created socket is closed in case of a general SSL error, but it's not closed in case of CertificateHostnameMismatchError (as ssl module doesn't provide hostname checking and it's done by httplib2 code). So when the second request is performed, connect() is not called, because the connection has already been created, and certificate hostname mismatch is not checked. 

Tested versions: the last commit of the default branch in hg repo; 0.7.2, 0.8.

A possible patch fixing this bug is attached.

**Attachment:** [ssl_hostname.diff](http://code.google.com/p/httplib2/issues/detail?id=282)

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=282_

**Comment by VanessaHenderson** [comment]
Can we please confirm if the lastest version (0.9.2) is vulnerable or not?

**Comment by djc** [comment]
@jcgregorio I'm surprised you're closing this security bug without further comment. Can you at least provide some rationale of why you think does not merit further attention?

**Comment by cdent** [comment]
If this is still relevant please re open it at https://github.com/httplib2/httplib2/issues

See: http://bitworking.org/news/2016/03/an_update_on_httplib2
