### ISSUE TITLE
httplib2-0.8 install error

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#245]
_From [nare...@google.com](https://code.google.com/u/115952439316878314995/) on May 02, 2013 10:36:00_

What steps will reproduce the problem? 1. Downloaded httplib2-0.8.zip
2. Extracted to lib/site-packages/
3. Tried to install package using 

C:\Python26>python.exe C:\python_26_amd64\files\Lib\site-pckages\httplib2-0.8\setup.py install

Getting error:
error: error in 'egg_base' option: 'python2' does not exist or is not a directory What is the expected output? What do you see instead? I expect package to be installed successfully What version of the product are you using? On what operating system? httplib2-0.8, Windows Server 2008 Enterprise 64 bit

Thanks
Naresh

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=284_

**Comment by zhouzhq** [comment]
I am experiencing the same error, I could not get it fixed so far.

**Comment by zhouzhq** [comment]
Finally I installed httplib2 via pip. 
Just try "python -m pip install httplib2" (I am using cygwin instead of windows cmd). 
If this does not work, you may also want to try "python -m easy_install httplib2".

To be specific, you need to make sure pip (or easy_install) is already installed with your python.

**Comment by zhouzhq** [comment]
Oh, I just found an easier way to install packages via PyCharm. If there is a module cannot be found, there will be an error pops up and a hint to prompt you to install package. Choose that option will install the package for you.
