### ISSUE TITLE
cacerts.txt permissions

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#252]
_From [jdew...@gmail.com](https://code.google.com/u/101575746756614478075/) on August 09, 2013 19:47:37_

What steps will reproduce the problem? 1. A client which uses httplib2 https://github.com/openstack/python-neutronclient/blob/quantumclient/quantumclient/client.py#L102 2. The client is used inside a django app https://github.com/openstack/horizon/blob/stable/grizzly/openstack_dashboard/api/cinder.py#L54 What is the expected output? What do you see instead? Apache is unable to read cacerts.txt which contains the wrong permissions, and returning:

[Tue Aug 06 14:19:49 2013] [error] \x1b[31;1mRecoverable error: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib\x1b[0m

$ ls -l /usr/local/lib/python2.7/dist-packages/httplib2/cacerts.txt
-rw-r----- 1 root staff 39670 Jul 29 18:05 /usr/local/lib/python2.7/dist-packages/httplib2/cacerts.txt What version of the product are you using? On what operating system? - Ubuntu 12.04
- Python 2.7.3
- python-httplib2 0.7.2-1ubuntu2

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=292_

**Comment by jlec** [comment]
So the restrictive permissions for cacerts.txt are by accident not forcibly?

**Comment by redlolgeerf** [comment]
+1 got the same issue

**Comment by zerthimon** [comment]
+1 same problem.

P.S
Why should PUBLIC ca certificates be restriced ?

**Comment by 0-wiz-0** [comment]
What was the solution? I see this with the 0.9.2 tarball.

**Comment by jayvdb** [comment]
See README in this repo
