### ISSUE TITLE
Using FeedParser causes incompatibility with Python 2.3

### ISSUE THREAD

**Issue by jcgregorio** [jcgregorio/httplib2#255]
_From [ondra...@gmail.com](https://code.google.com/u/103236129668617923440/) on November 04, 2013 04:57:59_

Because of importing email.FeedParser, the library is incompatible with Python 2.3 which is still declared as supported.

Tested with Python 2.3.5 on Windows 7. According to Python documentation, FeedParser is a new feature in Python 2.4, so it probably wouldn't work on any platform.

I would recommend either to use email.Parser instead, or drop the compatibility with Python 2.3.

_Original issue: http://code.google.com/p/httplib2/issues/detail?id=298_

**Comment by wldcordeiro** [comment]
Just support 2.6+ it makes a lot more sense now and simplifies supporting 2 and 3.
