### ISSUE TITLE
httplib.ResponseNotReady raised for basic authenticated connections

### ISSUE THREAD

**Issue by tdierks** [jcgregorio/httplib2#284]
I have a server that uses a web service which uses HTTP Basic Authentication to authenticate the service and uses httplib2 as the client (Twilio). As seen in twilio/twilio-python#166, calling the API sometimes raises a `httplib.ResponseNotReady` exception.

In looking at the code, I couldn't see any way that Twilio's client could be misusing the http connection object in the fashions I understand can lead to `ResponseNotReady`. As you can see in [the code] (https://github.com/twilio/twilio-python/blob/e0125860d78887e00b2dcce6917eea9356f5f77c/twilio/rest/resources/base.py#L76), it constructs a new `Http` object and falls through directly to `Http.request` in line 115 without any code paths that might allow reuse.

Twilio uses Basic authentication, and since the first request doesn't include the necessary auth parameters, the server gives a 401 response and then the request is retried. This happens for every request through this API client. Looking at the code which actually results in the `ResponseNotReady` exception, I can see that it is thrown from the retry, from [this line] (https://github.com/jcgregorio/httplib2/blob/e79528290bb60929f0b6a662c5832e9bd59c0dfb/python2/httplib2/__init__.py#L1361).

From reading the httplib source, specifically `httplib.HTTPConnection.getresponse()` and relevant [StackOverflow questions] (http://stackoverflow.com/questions/3231543/python-httplib-responsenotready), this is thrown when the connection object cannot be used because the response from a previous connection hasn't yet been consumed. This causes me to suspect that there is a race condition of some kind which occasionally leads to the HTTPConnection object being in this bad state at the time the httplib2 library attempts to go for the second request after the 401 response.

I don't understand the internals well enough to find the bug by inspection and haven't built a reproducible test case, but I'm hoping this information and hypothesis is sufficient to help someone who is more expert to find the problem, if I'm correct and it's a client-side issue. That said, it may make sense for httplib2 to catch the ResponseNotReady error and retry with a new connection object if a server or connectivity problem can cause such an ephemeral issue.

There are other StackOverflow questions which indicate that other users run into this problem with other services, as well.

**Comment by dhermes** [comment]
@jcgregorio Ditto

**Comment by jayvdb** [comment]
Is this occurring only on Python 2?

**Comment by dellsystem** [comment]
Seeing this with the [Python Instagram client](https://github.com/Instagram/python-instagram). v2.7.6.

**Comment by neokril** [comment]
I have 100% reproduce rate of this error with oauth2client 1.5.0 and Python 2.7.6 on windows 7 x64.

The failing code:
```
    home_dir = os.path.expanduser('~')
    credential_dir = os.path.join(home_dir, '.credentials')
    if not os.path.exists(credential_dir):
        os.makedirs(credential_dir)
    credential_path = os.path.join(credential_dir,
                                   'calendar-quickstart.json')

    print oauth2client
    store = oauth2client.file.Storage(credential_path)
    credentials = store.get()
    if not credentials or credentials.invalid:
        flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
        flow.user_agent = APPLICATION_NAME
        #flags = None
        #if flags:
        #    credentials = tools.run_flow(flow, store, flags)
        #else: # Needed only for compatability with Python 2.6
        credentials = tools.run_flow(flow, store, flags)
```

(It's an example from https://developers.google.com/google-apps/calendar/quickstart/python)

It always fail on the second step of authentication with the following backtrace:
```
  File "C:/Python27/my/telegram_bot\gcal_service.py", line 54, in main
    credentials = get_credentials()
  File "C:/Python27/my/telegram_bot\gcal_service.py", line 44, in get_credentials
    credentials = tools.run_flow(flow, store, flags)
  File "gcal\oauth2client\util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "gcal\oauth2client\tools.py", line 231, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "gcal\oauth2client\util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "gcal\oauth2client\client.py", line 2132, in step2_exchange
    headers=headers)
  File "gcal\httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "gcal\httplib2\__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "gcal\httplib2\__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "C:\Python27\lib\httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
ResponseNotReady
```

**Comment by dhermes** [comment]
Seems there was a post from "Dmitry" that got deleted. I'd love to look into this (may be a Windows specific issue).

----

I have 100% reproduce rate of this error with oauth2client 1.5.0 and Python 2.7.6 on windows 7 x64.

The failing code:

```python
home_dir = os.path.expanduser('~')
credential_dir = os.path.join(home_dir, '.credentials')
if not os.path.exists(credential_dir):
    os.makedirs(credential_dir)
credential_path = os.path.join(credential_dir,
                               'calendar-quickstart.json')

print oauth2client
store = oauth2client.file.Storage(credential_path)
credentials = store.get()
if not credentials or credentials.invalid:
    flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
    flow.user_agent = APPLICATION_NAME
    #flags = None
    #if flags:
    #    credentials = tools.run_flow(flow, store, flags)
    #else: # Needed only for compatability with Python 2.6
    credentials = tools.run_flow(flow, store, flags)
```

(It's an example from https://developers.google.com/google-apps/calendar/quickstart/python)

It always fail on the second step of authentication with the following backtrace:

```python
  File "C:/Python27/my/telegram_bot\gcal_service.py", line 54, in main
    credentials = get_credentials()
  File "C:/Python27/my/telegram_bot\gcal_service.py", line 44, in get_credentials
    credentials = tools.run_flow(flow, store, flags)
  File "gcal\oauth2client\util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "gcal\oauth2client\tools.py", line 231, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "gcal\oauth2client\util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "gcal\oauth2client\client.py", line 2132, in step2_exchange
    headers=headers)
  File "gcal\httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "gcal\httplib2\__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "gcal\httplib2\__init__.py", line 1306, in _conn_request
    response = conn.getresponse()
  File "C:\Python27\lib\httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
ResponseNotReady
```

**Comment by dhermes** [comment]
I just fired up a Windows machine and **cannot** reproduce.

**Comment by dellsystem** [comment]
For the record, I've been getting this error on Ubuntu 14.04 with the Instagram API, but it's sporadic and I can't reproduce it on demand.

**Comment by dhermes** [comment]
Really helpful, thanks! @dellsystem Do you have a snippet that causes it sporadically so I could run it (my OS is also Ubuntu 14.04)?

We've seen this as well: GoogleCloudPlatform/gcloud-python#575 and just went with `httplib` in the situation that caused it.

**Comment by dhermes** [comment]
@dellsystem #313 may explain the issue.

I tried to reproduce with code that used to fail, but I think my connection isn't flaky enough to cause it. To **try** to replicate it, I did:

```
git clone https://github.com/GoogleCloudPlatform/gcloud-python/
cd gcloud-python/
# Determine PR parent from
# https://api.github.com/repos/GoogleCloudPlatform/gcloud-python/pulls/577/commits
git branch pr-577 bf93d461298d0980a41c5dfa426d9f32af3d42fb
git checkout pr-577
# We use .tox/py27/bin/nosetests, so we need to (re)create the environ
tox -e py27 --recreate
cat <<EOF > a.sh
#!/bin/bash

set -e

for i in \$(seq 1 40);
do
    .tox/py27/bin/nosetests gcloud/datastore/test___init__.py > /dev/null 2>&1
    echo "Attempt \${i}: status \${?}"
done
EOF
chmod +x a.sh
./a.sh
```

**Comment by ccstolley** [comment]
@dhermes We saw this error extensively when using the Instagram python client, particularly when our connectivity to Instagram's API is hindered by network hiccups and the like. The patch in #313 fixed it for us.

**Comment by dhermes** [comment]
I really appreciate that you guys chased it down!

**Comment by dellsystem** [comment]
@ccstolley :+1: I'm glad someone figured it out! Thanks!
