### ISSUE TITLE
I need a help because github say "I am a robot"

### ISSUE THREAD

**Issue by TonyPythoneer** [jcgregorio/httplib2#294]
I just look this repository but I get this message suddenly:

"""
One of our mostly harmless robots seems to think you are not a human.
Because of that, it's hidden your profile from the public. If you really are human, please contact support to have your profile reinstated.
We promise we won't require DNA proof of your humanity.
"""

when I click  "contact support", it tell me:

"""
Troubles with jcgregorio/httplib2?
jcgregorio can probably help you better than GitHub Support can. You might want to open an issue or send them an email.
"""

so, I need jcgregorio who helps me to slove this problem. thanks!

**Comment by hhsadiq** [comment]
I also got this exact problem. They blocked my profile from public. I reported this problem at support and profile was restored in less than half an hour. I think github guys have programmed their NOT SO HARMLESS robot with some weird too-strict rules. They definitely need to revise their policy, it is giving too many false positives.
