### ISSUE TITLE
len(content) not equal to 0 even if using "HEAD" method

### ISSUE THREAD

**Issue by princeedward** [jcgregorio/httplib2#299]
Hi there,

I got a little bit confused by the 'method' argument of  the request() function(class Http). I thought if I specify the method to "HEAD", then only response headers will be returned and the response body will be empty. It was true for most of the cases. But the following piece of code will return the response body. I think it could be a bug somewhere in the code, because I tried to use telnet to make the same requests and the "HEAD" method works just fine. I hope this information is helpful. Thanks.

<pre>
import httplib2
h = httplib2.Http()
resp, content = h.request("http://www.taobao.com", method="HEAD")
print len(content)
</pre>

The output is: 175493

The python version is: 
2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]

The httplib2 version is: 0.9.1

**Comment by jcgregorio** [comment]
If the server returned any content in response to a HEAD request then it's a bug in the server, not httplib2.

**Comment by princeedward** [comment]
I used 'telnet' to send the "HEAD" request to the server directly and it didn't return any body, that is why I think there is a bug somewhere in library.
