### ISSUE TITLE
The examples page has several instances of unformatted code

### ISSUE THREAD

**Issue by PlasmaSheep** [jcgregorio/httplib2#305]
https://github.com/jcgregorio/httplib2/wiki/Examples

I'd fix them myself but it doesn't seem like I have edit permissions.

**Comment by PlasmaSheep** [comment]
Why was this closed? It doesn't appear to be fixed.

**Comment by jayvdb** [comment]
http://bitworking.org/news/2016/03/an_update_on_httplib2

**Comment by cdent** [comment]
If this is still relevant please reopen it with the necessary details at https://github.com/httplib2/httplib2/issues
