### ISSUE TITLE
jython compile issue with httplib2 module

### ISSUE THREAD

**Issue by jaehokim00** [jcgregorio/httplib2#306]
I wrote a python file to use httplib2 . I have 2.6.9 python and also jython 2.7

when I compile python it was creating .pyc and worked fine , but when I tried to use with robot framework which I use jython to create .class failed

 /Users/jaehokim00/jython2.7.0/bin/jython RestLib.py
Traceback (most recent call last):
  File "RestLib.py", line 5, in <module>
    import httplib2
  File "/Library/Python/2.6/site-packages/httplib2/__init__.py", line 59, in <module>
    from httplib2 import socks
  File "/Library/Python/2.6/site-packages/httplib2/__init__.py", line 59, in <module>
    from httplib2 import socks
  File "/Library/Python/2.6/site-packages/httplib2/socks.py", line 116, in <module>
    class socksocket(socket.socket):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str

Not sure how I can resolve this , it would be great if you have any suggestion

**Comment by caio2k** [comment]
try this quick hack in socks.py:
-import socket
+from socket import socket

**Comment by tmatsuo** [comment]
This bug prevents developers from using httplib2 and other libraries with Jython. Let's fix this. I'll open a PR.

**Comment by tmatsuo** [comment]
There is already a PR for this issue at:
https://github.com/jcgregorio/httplib2/pull/300
