### ISSUE TITLE
no_proxy does not support CIDR notation

### ISSUE THREAD

**Issue by JohnVillalovos** [jcgregorio/httplib2#323]
If someone wants to use a value of:
no_proxy=10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,172.16.0.0/12

It will not work.

I notice the requests library has logic where it checks to see if the value is_valid_cidr and if so then see if the destination IP address_in_network

https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L493-L510

https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L463-L473

Maybe some ideas on how to implement it in httplib2

**Comment by JohnVillalovos** [comment]
Was this fixed?  Is that why it was closed?

**Comment by jcgregorio** [comment]
Please Note: This repo is deprecated.

Please use the new repo at https://github.com/httplib2.

See also: http://bitworking.org/news/2016/03/an_update_on_httplib2
