### ISSUE TITLE
With Python3.5 disable_ssl_certificate_validation appears being ignored

### ISSUE THREAD

**Issue by gitjoost** [jcgregorio/httplib2#324]
Using python3.5 and httplib2 0.9.2 the following code fails with:
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)

    import httplib2
    url = 'https://www.MyTestServer.com/Test'
    h = httplib2.Http(".cache", disable_ssl_certificate_validation=True)
    h.add_credentials('username', 'password')
    resp, content = h.request(url, 'GET')

**Comment by cathalgarvey** [comment]
Same. There's a PR to fix this from literally years ago that hasn't been accepted, is this repository still being maintained?

**Comment by cdent** [comment]
Please reopen this issue with relevant details over at https://github.com/httplib2/httplib2 where future maintenance will be happening.
