### ISSUE TITLE
Fail to validate HTTPS server while using custom CA file

### ISSUE THREAD

**Issue by drmalex07** [jcgregorio/httplib2#325]
Hello httplib2.
I am using httplib2==0.9.2.

My use case is quite simple: we have a private network and have setup some HTTPS services. These services provide certificates signed by a site-local CA authority. All certificates are signed using SHA-256 as signing algorithm.

Take that: 
  * a self-signed root CA certificate exists inside `/etc/ssl/certs/ca-certificates.crt`  (the standard debian location)
  * the certificate for CN `foo.localdomain` is signed by this local authority, and is installed to a web server https://foo.localdomain

I'am trying to use httplib2 to communicate with this service: 
```python
h = httplib2.Http(ca_certs='/etc/ssl/certs/ca-certificates.crt')
resp, cont = h.request('https://foo.localdomain')
``` 

The above fails to perform a proper handshake, but unfortunately it returns poor feedback on where the actual problem is:
```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    resp, cont = h.request('https://foo.localdomain')
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

At the same time, the following `s_client` test succeeds (certificate verification returns `0`):
```
openssl s_client -connect foo.localdomain:443 -servername foo.localdomain -CAfile /etc/ssl/certs/ca-certificates.crt
```

Also, `curl` succeeds:
```
curl --cacert /etc/ssl/certs/ca-certificates.crt https://foo.localdomain
```

**Comment by drmalex07** [comment]
Hello, any feedback on this?

**Comment by kwerey** [comment]
I'm hitting a similar error once I've added an internal certificate authority into the Centos certificate store. openssl s_client and curl trust the remote host, but certificate verification fails in httplib2 even when it's explicitly pointed at the store.
  
Expected behaviour: if I'm specifying a store explicitly, the store should either be used or an error should be given back if httplib2 needs them in a specific format/with specific permissions/anything else.

Actual behaviour: certificate verification fails, but without telling me how or why, or giving me enough information to know if my ca_certs value is actually being used.

```
>>> conn.ca_certs
'/etc/pki/tls/certs/ca-bundle.crt'
>>> conn.request("[server.with.internally.trusted.wildcard.cert.com]", 443)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

openssl s_client:
```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
[...]
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by cdent** [comment]
Please reopen this issue with relevant details over at https://github.com/httplib2/httplib2 where future maintenance will be happening.
