### ISSUE TITLE
httplib2.Http() generates cache keys that exceed memcached max length

### ISSUE THREAD

**Issue by Alex3917** [jcgregorio/httplib2#327]
I'm creating an Http object with a cache like so:

httplib2.Http(cache=cache)

This fails when my API calls have long querystrings, because the max length of a memcached key is 250. As a proposed solution, maybe a hash of the querystring could be used as the cache key instead.

**Comment by cdent** [comment]
Please reopen this issue with relevant details over at https://github.com/httplib2/httplib2 where future maintenance will be happening.
