### ISSUE TITLE
Python 3 trove classifier now missing from PyPI page

### ISSUE THREAD

**Issue by cclauss** [jcgregorio/httplib2#333]
https://pypi.python.org/pypi/httplib2/0.9.2 contains the `Programming Language :: Python :: 3` trove classifier but https://pypi.python.org/pypi/httplib2/0.10.3 does not.  This means that scripts can no longer automatically determine if httplib2 is Python 3 compatible or not.

**Comment by jcgregorio** [comment]
Please Note: This repo is deprecated

Please use the new repo at https://github.com/httplib2.
